### PR TITLE
V0.15.0 updates

### PR DESCRIPTION
**Pull request by paluh**
* I was able to force the compilation of the test module by introducing an extra constraint.

* Additionally I dropped instance names.

### CODE REVIEW

**Comment by paluh** [comment]
This should solve the problem with the original PR to the original repo: https://github.com/paf31/purescript-foreign-generic/pull/75#issuecomment-1140225903

**Comment by paluh** [comment]
@sigma-andex , @i-am-the-slime, @JordanMartinez - really sorry for spamming but I noticed that this repo is not watched by anyone so this PR gonna be ignored by you Guys ;-)

**Comment by sigma-andex** [comment]
I think this working group is closed anyway. Maybe it makes sense to transfer or fork that repo to `purescript-contrib` and fix it there?

**Comment by paluh** [comment]
Hi @sigma-andex!

I provided the PR because there is an open PR (which I linked above) to purescript-foreign-generic based on this repo: https://github.com/paf31/purescript-foreign-generic/pull/75#issuecomment-1140225903

Do you think that I should close this one and go ahead and provide a separate PR to the foreign-generic instead?

**Comment by sigma-andex** [comment]
I don't think you'll get it merged if you open it to foreign-generic. I think the best bet is to ask Phil if he can transfer it to purescript-contrib.

**Comment by paluh** [comment]
@signa-andex are you able to merge this PR so the related PR gonna be updated?

Then we can ask for a merge and if that won't work we can start a discussion on the discord probably.

Does it sound ok to you?

**Pull request merged**
